### ISSUE TITLE
Socket connection sometimes breaks and can't be set up again

### ISSUE THREAD

**Issue by DiGyt** [magpie-ea/magpie-base#20]
Working with the chat component works usually completely smooth, however after some time working with it, it will often occur that the connection somehow just "breaks", meaning that two chat components aren't able to match up anymore and you're endlessly stuck in the `<ConnectInteractive />` lobby.

Clearing cookies, changing the browser from Firefox to Opera, restarting WebStorm/Ubuntu doesn't help, as the problem remains the same over days. After the connection was broken, the browser console constantly puts out: 

> Firefox can’t establish a connection to the server at wss://magpie-demo.herokuapp.com/socket/websocket?participant_id=88efcc028c68802683062e874ca2c25dd70500ac&experiment_id=171&vsn=2.0.0.

and
> [HTTP/1.1 403 Forbidden 583ms]

In fact, the same error even occurs on [the magpie documentation for the chat component](https://epic-bhabha-7e0966.netlify.app/#chat) at the current moment. I've got no idea how this socket stuff works under the hood, but my guess is that this "server" is broken and needs to be restarted.

@marcelklehr @x-ji What do you think of this problem? Do you have an idea how to fix it from happening again? Any suggestions on how to prevent it or how to handle it when it occurs?

Thanks for all the great work so far :)

**Comment by marcelklehr** [comment]
This is prolly one for @x-ji -- unless I'm doing something wrong?

**Comment by x-ji** [comment]
Hi @DiGyt thanks for the report. I looked into the source code of `magpie-base` and it's trying to submit to the experiment with ID 171 at the magpie demo site: https://magpie-demo.herokuapp.com/experiments/171/edit. I figured there were two reasons for the socket connection to be broken and fixed them. Now it should be working again:

1. For some reason, the experiment was set to "inactive" by somebody a while ago. I reactivated the experiment. This would already fail the attempt to establish a connection or submit experiment results. 
2. The server keeps track of "in progress" participants who have previously established a connection with the server. This tracker will be cleaned automatically upon a new deployment (which hasn't happened for a long time), or by clicking on the "reset experiment" button. I think there were probably too many connection attempts previously that were not terminated properly, so the server thinks that the maximum number of expected participants (2 * 2 * 20) is already reached for this experiment, and therefore automatically rejected new participants.
  I resolved it by using the "reset experiment" button. I will create a ticket to make the cleanup task periodic instead of depending on server redeployment. I think in the meanwhile another solution would be to use a higher number for expected participants for this chat demo experiment, which I would expect will be connected to quite often. If we want to keep the experiment id 171 so that we don't need to modify `magpie-base`, I will then modify the experiment specification manually in the backend.
 
I think the idea that the server is "broken" and needs to be restarted was not accurate, but I totally understand that it's impossible for the user to understand what's going on since no proper error message is being shown. I will also create a ticket to try to display better error messages which contain the reason when a socket connection doesn't succeed.

**Comment by x-ji** [comment]
Now I changed the experiment 171 to have 2 variants, 1000 chains and 1 realization, which I think semantically seems to make the most sense. I tried to connect to the socket using the old color-reference-game and it seems to work https://github.com/magpie-ea/magpie-color-reference. Please give it a try.

**Comment by DiGyt** [comment]
Seems to work now. Really nice and fast solution, thanks @x-ji  !
> I think the idea that the server is "broken" and needs to be restarted was not accurate

Yeah, sorry :laughing:. I'm really not into this.

**Comment by DiGyt** [comment]
Just saw the problem reoccurring (exactly the same as before), so I reopened this one.

But I forgot that the changes you've made will probably too only take effect after a new release, right?

**Comment by x-ji** [comment]
Hmm nope. Somebody (or something) disabled the experiment on Heroku again. I enabled it again and it should now work.

**Comment by x-ji** [comment]
You can also check the magpie-demo site first and check 1. the activation 2. the reset button if this happens again.

I will try to check whether a web crawler could have done this... But I think it was most likely done by a human being, so it's weird.

**Comment by x-ji** [comment]
Or I guess I'll finally need to get around to implementing https://github.com/magpie-ea/magpie-backend/issues/40 which would require an optional password when an experiment is modified.

**Comment by michael-franke** [comment]
There was also an error-log from the heroku demo instance about ‘memory quota exceeded’. Followed up by a time-out message. Could this be related?

**Comment by x-ji** [comment]
Yep, I also saw the errors

```
Feb 13 17:23:56 magpie-demo heroku/web.1: Error R14 (Memory quota exceeded)
Feb 13 17:24:12 magpie-demo heroku/router: at=error code=H12 desc="Request timeout" method=GET path="/experiments/93/retrieve" host=magpie-demo.herokuapp.com request_id=3321b483-f284-474f-9f63-f6493a85a7f5 fwd="88.198.17.136" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
Feb 13 17:25:01 magpie-demo heroku/router: at=error code=H12 desc="Request timeout" method=GET path="/experiments/retrieve_all" host=magpie-demo.herokuapp.com request_id=251778d1-8133-42cd-b707-e4cc4276806a fwd="88.198.17.136" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https
Feb 13 17:25:16 magpie-demo heroku/web.1: Error R14 (Memory quota exceeded)
```

and today

```
Feb 16 08:42:13 magpie-demo heroku/web.1: Error R14 (Memory quota exceeded)
Feb 16 08:42:19 magpie-demo heroku/router: at=error code=H12 desc="Request timeout" method=GET path="/experiments/retrieve_all" host=magpie-demo.herokuapp.com request_id=350cc003-cec6-49df-80da-adaa3e67c49a fwd="216.18.204.206" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=http
Feb 17 03:39:44 magpie-demo heroku/web.1: Error R14 (Memory quota exceeded)
Feb 17 03:39:50 magpie-demo heroku/router: at=error code=H12 desc="Request timeout" method=GET path="/experiments/retrieve_all" host=magpie-demo.herokuapp.com request_id=31193f8c-c999-4581-86a3-3c7ede146bf3 fwd="216.18.204.206" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
```

Seems that some experiment results got too large to be retrieved in time. I created another ticket for it https://github.com/magpie-ea/magpie-backend/issues/75

It's weird that somebody would be trying to retrieve the results for the experiment 93...... I always had a suspicion that it might be a bot after all, though I didn't expect it to also click on the button to disable an experiment. I will look into it further and see how we can prevent it.

By the way @michael-franke , do we still need the "retrieve_all" functionality on the Uni Osnabrueck server? Feels like this wouldn't make sense at least on the magpie-demo and it understandably led to a memory quota exceeded error under the current implementation. Or maybe we can let the user specify the IDs of several experiment results to retrieve instead of having a button to retrieve all?

**Comment by michael-franke** [comment]
Thanks for investigating!

> By the way @michael-franke , do we still need the "retrieve_all" functionality on the Uni Osnabrueck server? Feels like this wouldn't make sense at least on the magpie-demo and it understandably led to a memory quota exceeded error under the current implementation. Or maybe we can let the user specify the IDs of several experiment results to retrieve instead of having a button to retrieve all?

Based on past use, the ‘retrieve all’ functionality was never really important. I think it could just be skipped entirely. No need to replace it with manual selection, in my opinion.

**Comment by x-ji** [comment]
Cool. Thanks for the quick response. I'll create a ticket to remove that :)

**Comment by x-ji** [comment]
Tried to prevent web crawlers from accessing the page and removed the download all button. Let's see what happens.

**Comment by DiGyt** [comment]
Hate that I have to reopen this issue. But the error is occurring again :(

>Firefox can’t establish a connection to the server at wss://magpie-demo.herokuapp.com/socket/websocket?participant_id=88efcc028c68802683062e874ca2c25dd70500ac&experiment_id=171&vsn=2.0.0.

So far, resetting the respective experiment always worked, but now, it somehow didnt. :/

Any ideas why this is?

**Comment by marcelklehr** [comment]
It appears the experiment was deativated. I reactivated it. Can you try again?

**Comment by DiGyt** [comment]
Works again. Thanks a lot :)

Not sure why it didn't work for me though. Maybe I forgot to submit the new settings? 🤔
